version: 0.1
phases:
  pre_build:
    commands:
      - cd ..
      - mv ./src ./helloworld
      - cd helloworld
      - dotnet restore
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c Release -o out
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - out/**/*
    - appspec.yml
  discard-paths: no
