version: 0.1
phases:
  #install:
   # - 
  pre_build:
   commands:
   #   - dotnet restore
      - docker run -i --rm -v "$(pwd):/usr/src/helloworld" -w "/usr/src/helloworld" microsoft/dotnet:latest dotnet restore
  build:
    commands:
      - docker run -i --rm -v "$(pwd):/usr/src/helloworld" -w "/usr/src/helloworld" microsoft/dotnet:latest dotnet publish -c Release -o out
 #     - dotnet publish -c Release -o out
  post_build:
    commands:
      - $(aws ecr get-login)
      - docker build -t helloworld:latest .
      - docker tag helloworld:latest 242743551883.dkr.ecr.us-west-2.amazonaws.com/helloworld:latest
      - docker push 242743551883.dkr.ecr.us-west-2.amazonaws.com/helloworld:latest
#artifacts:
 # files:
    #- out/**/*
    #- appspec.yml
  #discard-paths: no
